### ISSUE TITLE
build.prop伪装代码不完整

### ISSUE THREAD

**Issue by ghost** [MiPushFramework/MiPushEnhancement#3]
如果该应用的原理如我所猜测的一样，是对应用伪装build. prop的话，根据应用内的描述来看，似乎没有修改 _ro.product.manufacturer=Xiaomi_ 这一项，经过控制变量测试后确认，部分应用不进行注册的原因就是因为缺少这一段。
我尝试自己做了个Magisk模块，经测暂未发现任何不能注册的应用（其他酷友也是），该模块的完整内容是
_ro.product.brand=Xiaomi
ro.product.manufacturer=Xiaomi
ro.miui.ui.version.code=10
ro.miui.ui.version.name=V12_
本人只算是个学习能力较强的小白，目前并没有任何apk以及xp开发/制作经验，比起从零开始学习，我更希望原作者能完善已有的项目。不排除该项目的原理并不是伪装build. prop，但如果以此方式实现的话就能做到配合虚拟框架**免解锁**注册，大大提高了兼容性并进一步降低使用门槛。

**Comment by MlgmXyysd** [comment]
https://github.com/MiPushFramework/MiPushEnhancement/blob/master/app/src/main/java/org/meowcat/xposed/mipush/Constants.java#L42
该条目已经伪装
